### ISSUE TITLE
Compiling with gfortran

### ISSUE THREAD

**Issue by ChristineTilling** [zorkzou/RelEPro#1]
While attempting to compile it with make, I get the following message:

```
RelEPro/source$ make
gfortran -c -o object/mod.o -O3 -Iobject -Jobject mod.f90
f951: Warning: Nonexistent include directory ‘object’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘object’ [-Wmissing-include-dirs]
mod.f90:290:19:

  290 | END MODULE Constant
      |                   1
Fatal Error: Cannot open module file ‘object/constant.mod0’ for writing at (1): No such file or directory
compilation terminated.
make: *** [Makefile:34: object/mod.o] Error 1
```

I cloned the repository to try to compile it, however if i am to listen to the warning some parts might need to be in a directory named object? I am running it through gfortran. When making a folder (in source) and naming it object i get a different error:

```
RelEPro/source$ make
gfortran -c -o object/mod.o -O3 -Iobject -Jobject mod.f90
gfortran -c -o object/int1e.o -O3 -Iobject -Jobject int1e.f90
int1e.f90:937:63:

  937 |         call PowerPAB(.true.,LQSum,ITYPE+LpVp,JTYPE+LpVp,aa,bb,gg,Ra,Rb,tmp,pab)
      |                                                               1
Error: Rank mismatch in argument ‘gg’ at (1) (scalar and rank-1)
int1e.f90:1108:62:

 1108 |       call PowerPAB(.false.,LQSum,ITYPE+LpVp,JTYPE+LpVp,aa,bb,gg,Ra,Rb,tmp,pab)
      |                                                              1
Error: Rank mismatch in argument ‘gg’ at (1) (scalar and rank-1)
make: *** [Makefile:37: object/int1e.o] Error 1

```

**Comment by ChristineTilling** [comment]
Further comments: I am running this on a Linux mint 21.1 (vera) system, and gfortran ver. 11.4.0.

**Comment by zorkzou** [comment]
Dear Christine,

There should be an empty folder "object" in source. Please create it.

Best regards,
Wenli

**Comment by ChristineTilling** [comment]
Dear Wenli

Like i wrote previously, I already did, in the meantime to make it compile I made a few small changes to the int1e.f90 and util.f90, both of which gave me mismatches between what the program expected and what it got, in the first case it gave me a rank mismatch error, where it expected a scalar and got an array of size 1, I modified the code to always take the first entry and expect an array. This was in the subroutine PowerPAB

In the case of the util.f90 the prtcoord subroutine runs a call of the ElemZA routine, this routine complained that it got a CHARACTER size 3 but expected a REAL(kind=8), I messed around with it for a bit trying different options for the placeholder variable zchar, and eventually got it to compile, whether it was as intended i do not know. 

I will upload the scripts as i got them to compile into a pull request. You can check if they are still doing what was intended, the values i get from the test do not seem completely off, nor does the output seem off.

Best Regards 
Christine

**Comment by zorkzou** [comment]
Thank you, Christine!

Since I have classes and graduation defenses in the recent days, I'll check
them this weekend.

Best regards,
Wenli
